# Generated by Django 5.1.3 on 2024-11-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_EVENTO', models.CharField(max_length=200)),
                ('FECHA', models.DateField()),
                ('DESCRIPCION', models.CharField(max_length=500)),
                ('IMAGEN', models.ImageField(upload_to='media')),
            ],
        ),
    ]
