# Generated by Django 5.1.3 on 2024-11-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_eventos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='IMAGEN',
            field=models.ImageField(null=True, upload_to='Eventos'),
        ),
    ]
