# Generated by Django 5.1.3 on 2024-11-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_eventos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_APELLIDO', models.CharField(max_length=200)),
                ('ACCION', models.CharField(max_length=200)),
                ('TESTIMONIO', models.CharField(max_length=800)),
            ],
        ),
    ]
