# Generated by Django 5.1.3 on 2024-11-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_testimonios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=200)),
                ('ESPECIE', models.CharField(max_length=200)),
                ('IMAGEN', models.ImageField(null=True, upload_to='ADOPTA')),
            ],
        ),
    ]
