# Generated by Django 5.1.3 on 2024-11-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_dona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dona',
            name='DIRECCION',
        ),
        migrations.RemoveField(
            model_name='dona',
            name='EMAIL',
        ),
    ]
