# Generated by Django 5.1.3 on 2024-11-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_dona_direccion_remove_dona_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonios',
            name='TESTIMONIO',
            field=models.TextField(),
        ),
    ]
